[package]
name = "file_navigator"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]

[dependencies]
conrod = {version = "0.61", features = ["glium", "winit"]}
glium = "0.22.0"
winit = "0.18.0"
find_folder = "0.3.0"
